class HomeController < ApplicationController
  def index

    jessica = Person.new("Jessica", "Torini")
    sam = Person.new("Sam", "Ellington")

    @registry = Registry.new([jessica, sam], Date.new(2014, 9, 20))
    @registry.story = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae nisi vitae purus semper auctor eget in mi. Proin augue libero, sodales et condimentum in, iaculis vitae ante. Vestibulum in facilisis dolor, sit amet tempus lacus. Aliquam erat volutpat. Pellentesque commodo ut dolor sed sollicitudin. Praesent sagittis diam ipsum, et viverra sapien mollis vel. Nunc sit amet risus sapien. Nullam vehicula tellus metus, sit amet suscipit augue elementum id. Nullam in ornare leo, id vulputate tortor.\n\nSed justo enim, ultricies quis volutpat non, consectetur ac dolor. Suspendisse sed leo ac ante pretium commodo vitae at dolor. Donec tempus vulputate odio, id fermentum velit gravida id. Nulla posuere erat ac ante euismod, et laoreet diam vulputate. Nam a turpis pharetra, iaculis sapien eget, lobortis orci. In hac habitasse platea dictumst. Nulla eu nulla vestibulum, ultrices elit sit amet, tincidunt libero. Integer fringilla dui nec rhoncus gravida. Sed vitae quam at nisl tincidunt condimentum tincidunt vel elit. Praesent sollicitudin ullamcorper nulla. Pellentesque eros nibh, posuere vel consequat porta, tristique non libero. Quisque eget ligula in ligula sagittis porta non ut justo. Nullam fermentum justo dolor, sed scelerisque velit lacinia vel."
    @registry.honeymoon_details = "Proin convallis enim massa, non laoreet nisl eleifend a. Sed ornare ante lorem, quis facilisis diam sodales eu. Praesent sed viverra purus. Maecenas bibendum laoreet lacus, ut ultrices leo aliquet non. Donec venenatis ultrices massa, quis interdum lorem dignissim eget. Donec volutpat diam vel dapibus porttitor. Nulla facilisi. Maecenas et urna et nulla hendrerit egestas. Quisque pharetra purus id condimentum vestibulum. Pellentesque mollis lectus tellus. In nunc ante, tincidunt eu ante ac, placerat vulputate erat. Cras pharetra est leo, placerat rutrum turpis cursus eu. Nunc tristique purus augue, a scelerisque risus commodo et."
    @registry.cover_image = "http://belize-travel-blog.chaacreek.com/wp-content/uploads/2011/04/honeymoon.jpg"

    dinner = RegistryItem.new("Dinner at Pirouette", 75.00, 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a imperdiet tortor. In hac habitasse platea dictumst. Morbi ullamcorper egestas erat, sed bibendum quam suscipit non. Etiam vel gravida diam, sed lacinia tellus. Aenean euismod faucibus ante. Pellentesque id gravida risus. Ut interdum non nulla malesuada cursus. Curabitur velit est, volutpat sed est nec, pretium euismod mauris. Quisque orci ante, laoreet et tortor rhoncus, fermentum pulvinar elit. Donec varius nisl sed lectus porttitor facilisis. Nam non ullamcorper ligula, non pulvinar tellus. Phasellus ac nibh ligula. Sed pulvinar lacus et condimentum luctus.", "http://simplyitickets.com/live/components/com_virtuemart/shop_image/product/CN_Tower_Dinner_4d0d171ce9621.jpg")
    hotel = RegistryItem.new("Four Seasons Hotel Room", 75.00, 8, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a imperdiet tortor. In hac habitasse platea dictumst. Morbi ullamcorper egestas erat, sed bibendum quam suscipit non. Etiam vel gravida diam, sed lacinia tellus. Aenean euismod faucibus ante. Pellentesque id gravida risus. Ut interdum non nulla malesuada cursus. Curabitur velit est, volutpat sed est nec, pretium euismod mauris. Quisque orci ante, laoreet et tortor rhoncus, fermentum pulvinar elit. Donec varius nisl sed lectus porttitor facilisis. Nam non ullamcorper ligula, non pulvinar tellus. Phasellus ac nibh ligula. Sed pulvinar lacus et condimentum luctus.", "http://thebuilderblog.files.wordpress.com/2008/03/burj_al_arab_3.jpg", "night")
    food = RegistryItem.new("Paris Food Tour", 200.00, 2, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a imperdiet tortor. In hac habitasse platea dictumst. Morbi ullamcorper egestas erat, sed bibendum quam suscipit non. Etiam vel gravida diam, sed lacinia tellus. Aenean euismod faucibus ante. Pellentesque id gravida risus. Ut interdum non nulla malesuada cursus. Curabitur velit est, volutpat sed est nec, pretium euismod mauris. Quisque orci ante, laoreet et tortor rhoncus, fermentum pulvinar elit. Donec varius nisl sed lectus porttitor facilisis. Nam non ullamcorper ligula, non pulvinar tellus. Phasellus ac nibh ligula. Sed pulvinar lacus et condimentum luctus.", "http://e3.vingle.net/c_limit,fl_progressive,q_85/zkxk3wkwe05yddhj0gw3.jpg")

    @registry.add_item(dinner)
    @registry.add_item(hotel)
    @registry.add_item(food)
    @registry.add_item(hotel)
    @registry.add_item(food)
    @registry.add_item(dinner)
  end
end
